# Generated by Django 3.0.6 on 2020-06-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dnews_titles', models.CharField(max_length=255)),
                ('dnews_links', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='N_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnews_titles', models.CharField(max_length=255)),
                ('nnews_links', models.URLField()),
            ],
        ),
    ]
